name: Firmware build

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    repository_dispatch:
        types: [remote_changed]   
    workflow_dispatch:

env:
    BUILD_TYPE: Release

jobs:
    build:
        permissions:
            contents: write
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y \
                    build-essential \
                    cmake \
                    gcc-arm-none-eabi \
                    unzip

            - name: Install Wonderful Toolchain
              run: |
                  curl -L -O "https://wonderful.asie.pl/bootstrap/wf-bootstrap-x86_64.tar.gz"
                  sudo mkdir /opt/wonderful
                  sudo chown -R "$USER" /opt/wonderful
                  tar -xzvf wf-bootstrap-x86_64.tar.gz -C /opt/wonderful
                  yes | /opt/wonderful/bin/wf-pacman -Syu wf-tools
                  source /opt/wonderful/bin/wf-env

            - name: Install BlocksDS
              run: |
                  export PATH=/opt/wonderful/bin:$PATH
                  yes | wf-config repo enable blocksds
                  yes | wf-pacman -Syu
                  yes | wf-pacman -S blocksds-toolchain
                  ln -s /opt/wonderful/thirdparty/blocksds /opt/blocksds

            - uses: actions/checkout@v4
              with:
                  repository: LNH-team/dspico-bootloader
                  submodules: recursive
                  fetch-depth: 0
                  path: dspico-bootloader

            - name: Build arm7, arm9.elf
              run: |
                  cd dspico-bootloader
                  make

            - uses: actions/checkout@v4
              with:
                  repository: LNH-team/dspico-firmware
                  submodules: recursive
                  fetch-depth: 0
                  path: firmware

            - name: Copy dummy1
              run: |
                  cp ./dummy1.bin ./firmware/roms/default.nds

            - name: Build firmware
              run: |
                  cd ./firmware
                  ./compile.sh

            - name: Copy uf2
              run: |
                  cp ./firmware/build/DSpico.uf2 ./firmware/DSpico1.uf2

            - name: Copy dummy2
              run: |
                  cp ./dummy2.bin ./firmware/roms/default.nds

            - name: Build firmware
              run: |
                  cd ./firmware
                  ./compile.sh

            - name: Copy uf2
              run: |
                  cp ./firmware/build/DSpico.uf2 ./firmware/DSpico2.uf2

            - name: Save build info
              run: |
                  > last_shas.txt
                  cd ./firmware
                  echo "FIRMWARE=$(git rev-parse HEAD)" >> ../last_shas.txt
                  cd ../dspico-bootloader
                  echo "BOOTLOADER=$(git rev-parse HEAD)" >> ../last_shas.txt

            - name: Prepare deploy
              run: |
                  mkdir -p deploy
                  cp ./dspico-bootloader/build/arm7.elf deploy/
                  cp ./dspico-bootloader/build/arm9.elf deploy/
                  cp ./firmware/DSpico1.uf2 deploy/
                  cp ./firmware/DSpico2.uf2 deploy/
                  cp ./last_shas.txt deploy/
                  cp ./build_date.txt deploy/

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: deploy
                  force_orphan: true
                  user_name: "github-actions"
                  user_email: "github-actions@github.com"
